import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { PremiumProvider } from "@/context/PremiumContext";
import Navbar from "@/components/Navbar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { SubjectModal } from "@/components/modals/subject-modal";
import { Toaster } from "sonner";
import { Providers } from "@/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AiEdify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: undefined,
        variables: { colorPrimary: "#000000" },
        elements: {
          formButtonPrimary: "bg-blue-500 hover:bg-blue-600 text-sm normal-case",
        },
      }}
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      signInUrl='/sign-in'
      signUpUrl='/sign-up'
      afterSignInUrl='/tools'
      afterSignUpUrl='/user-type'
      waitlistUrl='/waitlist'
      allowedRedirectOrigins={[
        "https://app.aiedify.com",
        "https://accounts.aiedify.com",
        "https://clerk.aiedify.com",
        "https://edify-dev.vercel.app",
      ]}
    >
      <html lang='en' className={`${geistSans.variable} ${geistMono.variable}`}>
        <body className='min-h-screen flex flex-col'>
          <Providers>
            <PremiumProvider>
              <SidebarProvider>
                <Navbar />
                <main className='flex-1 pt-16'>{children}</main>
              </SidebarProvider>
            </PremiumProvider>
          </Providers>
          <SubjectModal />
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
